# -*- coding: utf-8 -*-
"""annotation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fFz5GfN7cvrbm96XjFJ_utX08VFxon9
"""

!pip install Bio
from Bio import Entrez
import pandas as pd


# Read your upregulated genes
df = pd.read_csv("upregulated_genes.csv")

Entrez.email = "jamesonuh2020@gmail.com"
# Select the top DEGs
top_genes = df["Unnamed: 0"].tolist()
annotations = []

print(f"Annotating {len(top_genes)} genes using NCBI...")

for gene in top_genes:
    try:
        # Search NCBI Gene
        search = Entrez.esearch(
            db="gene",
            term=f"{gene}[Gene Name] AND Saccharomyces cerevisiae[Organism]",
            retmax=1
        )

        result = Entrez.read(search)
        search.close()

        if not result["IdList"]:
            print(f"No NCBI Gene ID found for {gene}")
            continue

        gene_id = result["IdList"][0]

        # Retrieve gene record
        fetch = Entrez.efetch(
            db="gene",
            id=gene_id,
            retmode="xml"
        )

        record = Entrez.read(fetch)
        fetch.close()

        info = record[0]

        # Gene description
        gene_data = info.get("Entrezgene_gene", {})
        gene_ref = gene_data.get("Gene-ref", {})

        if isinstance(gene_ref, list):
            gene_ref = gene_ref[0] if gene_ref else {}

        description = gene_ref.get("Gene-ref_desc", "N/A")

        # Function summary
        function = info.get("Entrezgene_summary", "N/A")

        # GO and KEGG terms
        go_terms = []
        kegg_terms = []

        sections = [
            info.get("Entrezgene_gene", {}),
            info.get("Entrezgene_locus", [])
        ]

        for section in sections:

            if isinstance(section, dict):
                section = [section]

            for item in section:

                for commentary in item.get("Gene-commentary", []):

                    label = commentary.get("Gene-commentary_label")
                    text = commentary.get("Gene-commentary_text")

                    if label == "GO" and text:
                        go_terms.append(text)

                    elif label == "KEGG" and text:
                        kegg_terms.append(text)

        # Store result
        annotations.append({
            "Gene": gene,
            "NCBI_Gene_ID": gene_id,
            "Description": description,
            "Function": function,
            "GO_Terms": "; ".join(go_terms) if go_terms else "N/A",
            "KEGG_Terms": "; ".join(kegg_terms) if kegg_terms else "N/A"
        })

        print(f"Annotated: {gene}")

    except Exception as e:
        print(f"Error processing {gene}: {e}")


# Convert annotations to DataFrame
annotations_df = pd.DataFrame(annotations)

# Save results
annotations_df.to_csv("NCBI_gene_annotations.csv", index=False)

print("\nAnnotation complete!")
print("Results saved to NCBI_gene_annotations.csv")

result=pd.read_csv("NCBI_gene_annotations.csv")

result.head()

import os

old_filename = "NCBI_gene_annotations.csv"
new_filename = "annotations.csv"

if os.path.exists(old_filename):
    os.rename(old_filename, new_filename)
    print(f"File renamed from {old_filename} to {new_filename}")
else:
    print(f"File {old_filename} does not exist.")

